kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: open-pod-main
spec:
  podSelector: 
    matchLabels: 
      app: main-chart
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: 10.8.0.0/20
  ingress:
  - from:
    - ipBlock:
        cidr: 10.8.0.0/20