apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: auth-chart
  template:
    metadata:
      labels: 
        name: auth-chart
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: httpd
              containerPort: {{ .Values.service.port }}
              protocol: TCP