kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: open-pod-auth
spec:
  podSelector: 
    matchLabels:
      app: auth-chart
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - podSelector: 
        matchLabels:
          app: auth-chart
    - ipBlock:
        cidr: 10.12.0.0/20
  ingress:
  - from:
    - podSelector: 
        matchLabels:
          app: auth-chart
    - ipBlock:
        cidr: 10.12.0.0/20