kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: block-internet-auth
spec:
  podSelector: 
    matchLabels:
      name: auth-app
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.12.0.0/20