apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "containerization.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: 
      app: nginx-chart
  template:
    metadata:
      labels: 
        app: nginx-chart
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: demoapi-secret
              mountPath: /opt/certs
              readOnly: true
      volumes:
        - name: demoapi-secret
          secret:
            secretName: temp-demoapi-tls-secret