apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "containerization.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: 
      app: {{ .Values.app }}
  template:
    metadata:
      labels: 
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
              readOnly: {{ .Values.volume.readOnly }}
      volumes:
        - name: {{ .Values.volume.name }}
          secret:
            secretName: {{ .Values.volume.secretName }}