kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: open-public-nginx
spec:
  podSelector: 
    matchLabels: 
      app: nginx-chart
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0