apiVersion: v1
kind: Service
metadata:
  name: {{ include "containerization.fullname" . }}
  labels: 
    app: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.tport }}
      targetPort: {{ .Values.service.port }}
  selector: 
    app: {{ .Values.app }}
