kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: open-pod-database
spec:
  podSelector: 
    matchLabels:
      app: db-chart
  policyTypes:
    - Egress
    - Ingress
  egress:
  - to:
    - podSelector: 
        matchLabels:
          app: db-chart
    - ipBlock:
        cidr: 10.12.0.0/20
        except:
        - 10.12.13.40/32
  ingress:
  - from:
    - podSelector: 
        matchLabels:
          app: db-chart
    - ipBlock:
        cidr: 10.12.0.0/20
        except:
        - 10.12.13.40/32