apiVersion: v1
kind: Service # Create service
metadata:
  name: {{ include "database.fullname" . }}
  labels: 
    app: db-chart
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector: 
    app: db-chart
